import { FactorWeight } from './types';

export const FACTOR_WEIGHTS: FactorWeight[] = [
  // Economic (10)
  { key: 'fiscal_cost', label: 'Fiscal Cost', category: 'economic', weight: -0.9 },
  { key: 'deficit_pressure', label: 'Deficit Pressure', category: 'economic', weight: -0.8 },
  { key: 'subsidy_burden', label: 'Subsidy Burden', category: 'economic', weight: -0.7 },
  { key: 'price_sensitivity', label: 'Price Sensitivity', category: 'economic', weight: -0.5 },
  { key: 'inflation_risk', label: 'Inflation Risk', category: 'economic', weight: -0.6 },
  { key: 'growth_signal', label: 'Growth Signal', category: 'economic', weight: 0.7 },
  { key: 'jobs_multiplier', label: 'Jobs Multiplier', category: 'economic', weight: 0.8 },
  { key: 'capex_push', label: 'Capex Push', category: 'economic', weight: 0.5 },
  { key: 'consumption_boost', label: 'Consumption Boost', category: 'economic', weight: 0.6 },
  { key: 'tax_pressure', label: 'Tax Pressure', category: 'economic', weight: -0.4 },
  // Demographic (10)
  { key: 'population_affected', label: 'Population Affected', category: 'demographic', weight: 0.9 },
  { key: 'rural_ratio', label: 'Rural Ratio Fit', category: 'demographic', weight: 0.6 },
  { key: 'urban_ratio', label: 'Urban Ratio Fit', category: 'demographic', weight: 0.5 },
  { key: 'youth_share', label: 'Youth Share Fit', category: 'demographic', weight: 0.7 },
  { key: 'senior_share', label: 'Senior Share Fit', category: 'demographic', weight: 0.4 },
  { key: 'income_proxy_low', label: 'Low Income Fit', category: 'demographic', weight: 0.8 },
  { key: 'income_proxy_mid', label: 'Middle Income Fit', category: 'demographic', weight: 0.6 },
  { key: 'women_impact', label: 'Women Impact', category: 'demographic', weight: 0.5 },
  { key: 'migrant_impact', label: 'Migrant Impact', category: 'demographic', weight: 0.4 },
  { key: 'regional_equity', label: 'Regional Equity', category: 'demographic', weight: 0.5 },
  // Political (8)
  { key: 'incumbent_advantage', label: 'Incumbent Advantage', category: 'political', weight: 0.5 },
  { key: 'opposition_strength', label: 'Opposition Strength', category: 'political', weight: -0.9 },
  { key: 'regional_leaning', label: 'Regional Leaning', category: 'political', weight: 0.6 },
  { key: 'coalition_stability', label: 'Coalition Stability', category: 'political', weight: 0.5 },
  { key: 'cadre_strength', label: 'Cadre Strength', category: 'political', weight: 0.4 },
  { key: 'anti_incumbency', label: 'Anti-Incumbency', category: 'political', weight: -0.7 },
  { key: 'identity_alignment', label: 'Identity Alignment', category: 'political', weight: 0.6 },
  { key: 'local_leadership', label: 'Local Leadership', category: 'political', weight: 0.5 },
  // Behavioral (8)
  { key: 'turnout_elasticity', label: 'Turnout Elasticity', category: 'behavioral', weight: 0.8 },
  { key: 'welfare_sensitivity', label: 'Welfare Sensitivity', category: 'behavioral', weight: 0.8 },
  { key: 'aspiration_index', label: 'Aspiration Index', category: 'behavioral', weight: 0.7 },
  { key: 'trust_in_state', label: 'Trust in State', category: 'behavioral', weight: 0.4 },
  { key: 'benefit_salience', label: 'Benefit Salience', category: 'behavioral', weight: 0.7 },
  { key: 'policy_complexity_penalty', label: 'Policy Complexity Penalty', category: 'behavioral', weight: -0.6 },
  { key: 'fear_of_change', label: 'Fear of Change', category: 'behavioral', weight: -0.4 },
  { key: 'mobilization_energy', label: 'Mobilization Energy', category: 'behavioral', weight: 0.6 },
  // Media & perception (8)
  { key: 'visibility', label: 'Visibility', category: 'media', weight: 0.8 },
  { key: 'narrative_simplicity', label: 'Narrative Simplicity', category: 'media', weight: 0.7 },
  { key: 'controversy_probability', label: 'Controversy Probability', category: 'media', weight: -0.8 },
  { key: 'amplification_factor', label: 'Amplification Factor', category: 'media', weight: 0.5 },
  { key: 'misinfo_risk', label: 'Misinformation Risk', category: 'media', weight: -0.5 },
  { key: 'media_hostility', label: 'Media Hostility', category: 'media', weight: -0.6 },
  { key: 'earned_media', label: 'Earned Media', category: 'media', weight: 0.4 },
  { key: 'digital_reach', label: 'Digital Reach', category: 'media', weight: 0.6 },
  // Timing (6)
  { key: 'decay_factor', label: 'Memory Decay', category: 'timing', weight: -0.7 },
  { key: 'recency_boost', label: 'Recency Boost', category: 'timing', weight: 0.7 },
  { key: 'campaign_overlap', label: 'Campaign Overlap', category: 'timing', weight: 0.4 },
  { key: 'issue_fatigue', label: 'Issue Fatigue', category: 'timing', weight: -0.4 },
  { key: 'festival_cycle', label: 'Festival Cycle Fit', category: 'timing', weight: 0.3 },
  { key: 'budget_timing', label: 'Budget Timing', category: 'timing', weight: 0.4 },
  // Implementation (8)
  { key: 'leakage_risk', label: 'Leakage Risk', category: 'implementation', weight: -0.9 },
  { key: 'admin_capacity', label: 'Administrative Capacity', category: 'implementation', weight: 0.8 },
  { key: 'supply_constraints', label: 'Supply Constraints', category: 'implementation', weight: -0.7 },
  { key: 'last_mile_delivery', label: 'Last Mile Delivery', category: 'implementation', weight: 0.7 },
  { key: 'federal_alignment', label: 'Federal Alignment', category: 'implementation', weight: 0.5 },
  { key: 'it_infrastructure', label: 'IT Infrastructure', category: 'implementation', weight: 0.4 },
  { key: 'beneficiary_targeting', label: 'Beneficiary Targeting', category: 'implementation', weight: 0.6 },
  { key: 'auditability', label: 'Auditability', category: 'implementation', weight: 0.5 },

  // Advanced institutional & campaign (30)
  { key: 'judiciary_trust', label: 'Judiciary Trust', category: 'political', weight: 0.3 },
  { key: 'bureaucratic_alignment', label: 'Bureaucratic Alignment', category: 'implementation', weight: 0.6 },
  { key: 'federal_friction', label: 'Federal Friction', category: 'political', weight: -0.5 },
  { key: 'coalition_expansion_potential', label: 'Coalition Expansion Potential', category: 'political', weight: 0.4 },
  { key: 'policy_legality_risk', label: 'Policy Legality Risk', category: 'implementation', weight: -0.4 },
  { key: 'judicial_delay_risk', label: 'Judicial Delay Risk', category: 'implementation', weight: -0.3 },
  { key: 'grassroots_network_depth', label: 'Grassroots Network Depth', category: 'political', weight: 0.6 },
  { key: 'volunteer_conversion', label: 'Volunteer Conversion', category: 'behavioral', weight: 0.5 },
  { key: 'door_to_door_efficiency', label: 'Door-to-Door Efficiency', category: 'behavioral', weight: 0.4 },
  { key: 'event_turnout_quality', label: 'Event Turnout Quality', category: 'behavioral', weight: 0.4 },
  { key: 'message_consistency', label: 'Message Consistency', category: 'media', weight: 0.6 },
  { key: 'regional_language_fit', label: 'Regional Language Fit', category: 'media', weight: 0.5 },
  { key: 'spokesperson_credibility', label: 'Spokesperson Credibility', category: 'media', weight: 0.5 },
  { key: 'debate_performance', label: 'Debate Performance', category: 'media', weight: 0.4 },
  { key: 'fact_check_resilience', label: 'Fact-check Resilience', category: 'media', weight: 0.4 },
  { key: 'misinfo_counter_speed', label: 'Misinformation Counter Speed', category: 'media', weight: 0.5 },
  { key: 'crisis_response_speed', label: 'Crisis Response Speed', category: 'timing', weight: 0.5 },
  { key: 'candidate_favorability', label: 'Candidate Favorability', category: 'political', weight: 0.7 },
  { key: 'candidate_fatigue', label: 'Candidate Fatigue', category: 'political', weight: -0.4 },
  { key: 'women_turnout_elasticity', label: 'Women Turnout Elasticity', category: 'behavioral', weight: 0.5 },
  { key: 'youth_digital_mobilization', label: 'Youth Digital Mobilization', category: 'behavioral', weight: 0.6 },
  { key: 'elder_trust_resilience', label: 'Elder Trust Resilience', category: 'behavioral', weight: 0.3 },
  { key: 'festival_sensitivity', label: 'Festival Sensitivity', category: 'timing', weight: 0.3 },
  { key: 'monsoon_supply_shock', label: 'Monsoon Supply Shock', category: 'implementation', weight: -0.3 },
  { key: 'inflation_headline_pressure', label: 'Inflation Headline Pressure', category: 'economic', weight: -0.6 },
  { key: 'commodity_price_exposure', label: 'Commodity Price Exposure', category: 'economic', weight: -0.4 },
  { key: 'credit_access_signal', label: 'Credit Access Signal', category: 'economic', weight: 0.4 },
  { key: 'msme_sentiment', label: 'MSME Sentiment', category: 'economic', weight: 0.5 },
  { key: 'farmer_income_signal', label: 'Farmer Income Signal', category: 'economic', weight: 0.5 },
  { key: 'urban_cost_of_living_pressure', label: 'Urban Cost of Living Pressure', category: 'economic', weight: -0.5 },
];

export const BASELINE_FACTORS: Record<string, number> = Object.fromEntries(
  FACTOR_WEIGHTS.map((f) => [f.key, 0.5])
);
